name: Update CITATION.cff on Release

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-citation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version/date from release
        id: meta
        run: |
          TAG="${{ github.event.release.tag_name }}"
          # Strip a leading 'v' if present (e.g., v1.2.3 -> 1.2.3)
          VER="${TAG#v}"
          DATE="$(date -u +%Y-%m-%d)"
          echo "version=$VER" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Update CITATION.cff
        run: |
          python - << 'PY'
          import io, sys, datetime, yaml, os
          path = "CITATION.cff"
          with open(path, "r", encoding="utf-8") as f:
              data = yaml.safe_load(f)
          version = os.environ["VER"]
          date = os.environ["DATE"]
          data["version"] = version
          data["date-released"] = date
          # Keep preferred-citation year aligned with release year
          if "preferred-citation" in data:
              data["preferred-citation"]["year"] = int(date.split("-")[0])
          with open(path, "w", encoding="utf-8") as f:
              yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)
          PY
        env:
          VER: ${{ steps.meta.outputs.version }}
          DATE: ${{ steps.meta.outputs.date }}

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CITATION.cff
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(citation): bump to version ${{ steps.meta.outputs.version }} (release)"
            git push
          fi
